[package]
name = "transfix"
version = "0.1.0"
authors = ["Paul Ruane <paul.ruane@oniony.com>"]

[dependencies]
clap = { version = "4.3.19", features = ["cargo"]}
json = "0.11.13"
lazy_static = "1.4.0"
regex = "0.2"
