name: Build

on:
  push:
    branches: 
      - main
    paths:
      - Cargo.toml
      - src
      - README.md

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build CLI
      run: cargo build --verbose
