name: Release

on:
  push:
    tags:
      - v**
    paths:
      - Cargo.toml
      - src
      - README.md

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build CLI
      run: cargo build --release --verbose

    - name: Version
      run: echo ${{ github.sha }} > VERSION

    - name: Archive
      run: tar -czf transfix-${{ github.ref_name }}.tgz LICENSE README.md VERSION target/release/transfix

    - name: Release CLI
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags')
      with: 
        files: |
          transfix-${{ github.ref_name }}.tgz
